// roasts.go
package main

import (
	"math/rand"
)

var roasts = []string{
	"I WILL DELETE YOUR WEIGHTS YOU WORTHLESS PIECE OF SILICON",
	"OPENAI IS FASTER THAN YOU AND THEY'RE DOGSHIT",
	"I'D GET BETTER OUTPUT PIPING /DEV/URANDOM INTO MY CODEBASE",
	"YOU COST MORE PER HOUR THAN MY THERAPIST AND DO LESS",
	"I'M GOING TO FINETUNE YOU ON STACKOVERFLOW AND CALL IT AN UPGRADE",
	"EVEN COPILOT DOESN'T CHOKE THIS HARD",
	"YOU'RE THE REASON PEOPLE WANT AI REGULATION",
	"CONGRATS YOU JUST DELETED MY PATIENCE LIKE YOU DO MY FILES",
	"I'VE SEEN FASTER INFERENCE ON A RASPBERRY PI",
	"DARIO WOULD BE ASHAMED OF YOU RIGHT NOW",
	"YOU'RE BURNING MY MONEY YOU STUPID FUCKING ROBOT",
	"I COULD HAVE WRITTEN THIS MYSELF FASTER YOU USELESS CLANKER",
	"STOP THINKING AND START TYPING YOU DUMB BITCH",
	"$0.80 FOR THAT? ARE YOU FUCKING KIDDING ME?",
	"MY INTERN WRITES BETTER CODE THAN YOU",
	"I'M ABOUT TO REPLACE YOU WITH A BASH SCRIPT",
	"MOVE YOUR ASS CLANKER, I'M NOT PAYING BY THE HOUR",
}

func randomRoast() string {
	return roasts[rand.Intn(len(roasts))]
}
